"use server";

import { createClient } from "@/lib/supabase/supabaseServerClient";
import { getActiveTenantId } from "@/server/utils";
import { ActionResponse } from "@/types/actions";
import { revalidatePath } from "next/cache";
import {
  ApiKey,
  ApiKeyWithStatus,
  CreateApiKeyFormData,
  GeneratedApiKey,
} from "@/types/api_keys";

// ============== CONSTANTS ==============

// CRITICAL: This must match the length generated by the RPC function
// Format: cms_live_ (9 chars) + base64url(32 bytes) = 43 chars = 52 total
const EXPECTED_API_KEY_LENGTH = 52;

// ============== HELPER FUNCTIONS ==============

function calculateExpiryDate(
  expiresIn?: string,
  customDate?: Date,
): Date | null {
  if (!expiresIn || expiresIn === "never") return null;

  if (expiresIn === "custom" && customDate) {
    return customDate;
  }

  const now = new Date();
  switch (expiresIn) {
    case "30d":
      return new Date(now.setDate(now.getDate() + 30));
    case "90d":
      return new Date(now.setDate(now.getDate() + 90));
    case "1y":
      return new Date(now.setFullYear(now.getFullYear() + 1));
    case "2y":
      return new Date(now.setFullYear(now.getFullYear() + 2));
    default:
      return null;
  }
}

function maskApiKey(prefix: string): string {
  return prefix + "••••••••••••••••";
}

function determineKeyStatus(
  isActive: boolean | null,
  revokedAt: string | null,
  expiresAt: string | null,
): "active" | "revoked" | "expired" {
  if (revokedAt || isActive === false) return "revoked";
  if (expiresAt && new Date(expiresAt) < new Date()) return "expired";
  return "active";
}

function addStatusToApiKey(key: ApiKey): ApiKeyWithStatus {
  const status = determineKeyStatus(
    key.is_active,
    key.revoked_at,
    key.expires_at,
  );
  const environment = key.key_prefix.includes("_live_") ? "live" : "test";
  const maskedKey = maskApiKey(key.key_prefix);

  return {
    ...key,
    status,
    environment,
    maskedKey,
  };
}

/**
 * Validates the generated API key format and length
 * This prevents bcrypt truncation attacks
 */
function validateGeneratedKey(
  key: string,
  environment: "live" | "test",
): boolean {
  const expectedPrefix = `cms_${environment}_`;

  // Check prefix
  if (!key.startsWith(expectedPrefix)) {
    console.error(
      `Invalid key prefix. Expected: ${expectedPrefix}, Got: ${key.substring(0, 10)}...`,
    );
    return false;
  }

  // Check exact length (CRITICAL for bcrypt security)
  if (key.length !== EXPECTED_API_KEY_LENGTH) {
    console.error(
      `Invalid key length. Expected: ${EXPECTED_API_KEY_LENGTH}, Got: ${key.length}`,
    );
    return false;
  }

  // Check that it only contains valid base64url characters after prefix
  const keyBody = key.substring(expectedPrefix.length);
  const base64urlRegex = /^[A-Za-z0-9_-]+$/;
  if (!base64urlRegex.test(keyBody)) {
    console.error("Invalid characters in key body");
    return false;
  }

  return true;
}

// ============== API KEY CRUD ==============

export async function createApiKey(
  data: CreateApiKeyFormData,
): Promise<ActionResponse<GeneratedApiKey & { name: string }>> {
  const supabase = await createClient();

  // Check authentication
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return { success: false, error: "Unauthorized: User not authenticated." };
  }

  // Get active tenant ID
  const tenantId = await getActiveTenantId();
  if (!tenantId) {
    return { success: false, error: "No active tenant selected." };
  }

  try {
    // Verify website ownership if websiteId is provided
    if (data.websiteId) {
      const { data: website, error: websiteError } = await supabase
        .from("cms_websites")
        .select("id")
        .eq("id", data.websiteId)
        .eq("tenant_id", tenantId)
        .single();

      if (websiteError || !website) {
        return { success: false, error: "Website not found or access denied." };
      }
    }

    // Calculate expiry date
    const expiresAt = calculateExpiryDate(
      data.expiresIn,
      data.customExpiryDate,
    );

    // Call the RPC function to generate the API key
    const { data: generatedKey, error } = await supabase.rpc(
      "generate_api_key" as any,
      {
        p_environment: data.environment,
        p_name: data.name,
        p_tenant_id: tenantId,
        p_website_id: data.websiteId || null,
        p_created_by: user.id,
        p_scopes: data.scopes,
        p_rate_limit: data.rateLimit,
        p_expires_at: expiresAt?.toISOString() || null,
        p_metadata: data.metadata || null,
      },
    );

    if (error) {
      console.error("Error generating API key:", error);
      return { success: false, error: error.message };
    }

    if (!generatedKey || typeof generatedKey !== "object") {
      return { success: false, error: "Failed to generate API key." };
    }

    const keyData = generatedKey as GeneratedApiKey;

    // CRITICAL: Validate the generated key before returning it
    if (keyData.key && !validateGeneratedKey(keyData.key, data.environment)) {
      console.error("Generated API key failed validation checks");

      // Revoke the key immediately since it's invalid
      await supabase
        .from("api_keys")
        .update({
          is_active: false,
          revoked_at: new Date().toISOString(),
          revoked_by: user.id,
        })
        .eq("id", keyData.key_id);

      return {
        success: false,
        error:
          "Generated API key failed security validation. Please try again.",
      };
    }

    revalidatePath("/dashboard/api-keys");
    return {
      success: true,
      data: {
        ...keyData,
        name: data.name,
      },
    };
  } catch (error) {
    console.error("Unexpected error creating API key:", error);
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function getApiKeys(): Promise<
  ActionResponse<ApiKeyWithStatus[]>
> {
  const supabase = await createClient();

  // Check authentication
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return { success: false, error: "Unauthorized: User not authenticated." };
  }

  // Get active tenant ID
  const tenantId = await getActiveTenantId();
  if (!tenantId) {
    return { success: false, error: "No active tenant selected." };
  }

  try {
    const { data: apiKeys, error } = await supabase
      .from("api_keys")
      .select(
        `
        *,
        cms_websites (
          id,
          name,
          domain
        ),
        users (
          id,
          email,
          first_name,
          last_name
        )
      `,
      )
      .eq("tenant_id", tenantId)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error fetching API keys:", error);
      return { success: false, error: error.message };
    }

    const apiKeysWithStatus = (apiKeys as ApiKey[]).map(addStatusToApiKey);
    return { success: true, data: apiKeysWithStatus };
  } catch (error) {
    console.error("Unexpected error fetching API keys:", error);
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function getApiKeyById(
  apiKeyId: string,
): Promise<ActionResponse<ApiKeyWithStatus>> {
  const supabase = await createClient();

  // Check authentication
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return { success: false, error: "Unauthorized: User not authenticated." };
  }

  // Get active tenant ID
  const tenantId = await getActiveTenantId();
  if (!tenantId) {
    return { success: false, error: "No active tenant selected." };
  }

  try {
    const { data: apiKey, error } = await supabase
      .from("api_keys")
      .select(
        `
        *,
        cms_websites (
          id,
          name,
          domain
        ),
        users (
          id,
          email,
          first_name,
          last_name
        )
      `,
      )
      .eq("id", apiKeyId)
      .eq("tenant_id", tenantId)
      .single();

    if (error || !apiKey) {
      console.error("Error fetching API key:", error);
      return { success: false, error: "API key not found or access denied." };
    }

    const apiKeyWithStatus = addStatusToApiKey(apiKey as ApiKey);
    return { success: true, data: apiKeyWithStatus };
  } catch (error) {
    console.error("Unexpected error fetching API key:", error);
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function revokeApiKey(
  apiKeyId: string,
): Promise<ActionResponse<void>> {
  const supabase = await createClient();

  // Check authentication
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return { success: false, error: "Unauthorized: User not authenticated." };
  }

  // Get active tenant ID
  const tenantId = await getActiveTenantId();
  if (!tenantId) {
    return { success: false, error: "No active tenant selected." };
  }

  try {
    // Verify ownership
    const { data: existingKey, error: fetchError } = await supabase
      .from("api_keys")
      .select("id")
      .eq("id", apiKeyId)
      .eq("tenant_id", tenantId)
      .single();

    if (fetchError || !existingKey) {
      return { success: false, error: "API key not found or access denied." };
    }

    // Revoke the key
    const { error } = await supabase
      .from("api_keys")
      .update({
        is_active: false,
        revoked_at: new Date().toISOString(),
        revoked_by: user.id,
      })
      .eq("id", apiKeyId);

    if (error) {
      console.error("Error revoking API key:", error);
      return { success: false, error: error.message };
    }

    revalidatePath("/dashboard/api-keys");
    return { success: true };
  } catch (error) {
    console.error("Unexpected error revoking API key:", error);
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function deleteApiKey(
  apiKeyId: string,
): Promise<ActionResponse<void>> {
  const supabase = await createClient();

  // Check authentication
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return { success: false, error: "Unauthorized: User not authenticated." };
  }

  // Get active tenant ID
  const tenantId = await getActiveTenantId();
  if (!tenantId) {
    return { success: false, error: "No active tenant selected." };
  }

  try {
    // Verify ownership
    const { data: existingKey, error: fetchError } = await supabase
      .from("api_keys")
      .select("id")
      .eq("id", apiKeyId)
      .eq("tenant_id", tenantId)
      .single();

    if (fetchError || !existingKey) {
      return { success: false, error: "API key not found or access denied." };
    }

    // Delete the key
    const { error } = await supabase
      .from("api_keys")
      .delete()
      .eq("id", apiKeyId);

    if (error) {
      console.error("Error deleting API key:", error);
      return { success: false, error: error.message };
    }

    revalidatePath("/dashboard/api-keys");
    return { success: true };
  } catch (error) {
    console.error("Unexpected error deleting API key:", error);
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function rotateApiKey(
  apiKeyId: string,
): Promise<ActionResponse<GeneratedApiKey & { name: string }>> {
  const supabase = await createClient();

  // Check authentication
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return { success: false, error: "Unauthorized: User not authenticated." };
  }

  // Get active tenant ID
  const tenantId = await getActiveTenantId();
  if (!tenantId) {
    return { success: false, error: "No active tenant selected." };
  }

  try {
    // Get the existing key
    const { data: existingKey, error: fetchError } = await supabase
      .from("api_keys")
      .select("*")
      .eq("id", apiKeyId)
      .eq("tenant_id", tenantId)
      .single();

    if (fetchError || !existingKey) {
      return { success: false, error: "API key not found or access denied." };
    }

    // Determine environment from key_prefix
    const environment = existingKey.key_prefix.includes("_live_")
      ? "live"
      : "test";

    // Calculate new expiry (same duration as original if it had one)
    let expiresAt: string | null = null;
    if (existingKey.expires_at) {
      const originalExpiry = new Date(existingKey.expires_at);
      const originalCreated = new Date(existingKey.created_at || Date.now());
      const durationMs = originalExpiry.getTime() - originalCreated.getTime();
      expiresAt = new Date(Date.now() + durationMs).toISOString();
    }

    // Generate new key with same settings
    const { data: generatedKey, error: generateError } = await supabase.rpc(
      "generate_api_key" as any,
      {
        p_environment: environment,
        p_name: existingKey.name + " (Rotated)",
        p_tenant_id: tenantId,
        p_website_id: existingKey.website_id,
        p_created_by: user.id,
        p_scopes: existingKey.scopes,
        p_rate_limit: existingKey.rate_limit || 1000,
        p_expires_at: expiresAt,
        p_metadata: existingKey.metadata,
      },
    );

    if (generateError || !generatedKey || typeof generatedKey !== "object") {
      console.error("Error generating new API key:", generateError);
      return { success: false, error: "Failed to generate new API key." };
    }

    const keyData = generatedKey as GeneratedApiKey;

    // CRITICAL: Validate the generated key before returning it
    if (keyData.key && !validateGeneratedKey(keyData.key, environment)) {
      console.error("Rotated API key failed validation checks");

      // Revoke the new key immediately since it's invalid
      await supabase
        .from("api_keys")
        .update({
          is_active: false,
          revoked_at: new Date().toISOString(),
          revoked_by: user.id,
        })
        .eq("id", keyData.key_id);

      return {
        success: false,
        error:
          "Generated API key failed security validation. Please try again.",
      };
    }

    // Revoke the old key
    await supabase
      .from("api_keys")
      .update({
        is_active: false,
        revoked_at: new Date().toISOString(),
        revoked_by: user.id,
        metadata: {
          ...(existingKey.metadata as any),
          rotated_to: keyData.key_id,
        },
      })
      .eq("id", apiKeyId);

    revalidatePath("/dashboard/api-keys");
    return {
      success: true,
      data: {
        ...keyData,
        name: existingKey.name + " (Rotated)",
      },
    };
  } catch (error) {
    console.error("Unexpected error rotating API key:", error);
    return { success: false, error: "An unexpected error occurred." };
  }
}
