import {
  AlignLeft,
  BetweenHorizontalStart,
  Calendar,
  CheckSquare,
  ChevronsUpDown,
  FileUp,
  Hash,
  Heading,
  Link2,
  ListChecks,
  Mail,
  Minus,
  Phone,
  Pilcrow,
  SlidersHorizontal,
  Star,
  TextCursorInput,
  ToggleLeft,
  Type,
} from "lucide-react";
import { CheckboxFieldSettings } from "./field-settings/checkbox-field-settings";
import { ChoiceFieldSettings } from "./field-settings/choice-field-settings";
import { DateFieldSettings } from "./field-settings/date-field-settings";
import { FileFieldSettings } from "./field-settings/file-field-settings";
import { HeadingFieldSettings } from "./field-settings/heading-field-settings";
import { NumberFieldSettings } from "./field-settings/number-field-settings";
import { ParagraphFieldSettings } from "./field-settings/paragraph-field-settings";
import { RatingFieldSettings } from "./field-settings/rating-field-settings";
import { SelectFieldSettings } from "./field-settings/select-field-settings";
import type { BuilderField, BuilderFieldType, FieldTypeDefinition } from "./types";

function createDefaultField(type: BuilderFieldType, index: number): BuilderField {
  const baseLabel = `${type[0].toUpperCase()}${type.slice(1)} field`;
  return {
    id: crypto.randomUUID(),
    type,
    key: `${type}_${index + 1}`,
    label: baseLabel,
    required: true,
    placeholder: type === "checkbox" ? undefined : "Value here...",
    helpText: "Helper text",
  };
}

export const FIELD_TYPE_DEFINITIONS: Record<BuilderFieldType, FieldTypeDefinition> = {
  text: {
    type: "text",
    label: "Text Field",
    icon: Type,
    createField: (index) => createDefaultField("text", index),
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  email: {
    type: "email",
    label: "Email Field",
    icon: Mail,
    createField: (index) => createDefaultField("email", index),
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  textarea: {
    type: "textarea",
    label: "TextArea Field",
    icon: Pilcrow,
    createField: (index) => createDefaultField("textarea", index),
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  number: {
    type: "number",
    label: "Number Field",
    icon: Hash,
    createField: (index) => ({
      ...createDefaultField("number", index),
      min: undefined,
      max: undefined,
      step: 1,
    }),
    SettingsComponent: NumberFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  checkbox: {
    type: "checkbox",
    label: "CheckBox Field",
    icon: CheckSquare,
    createField: (index) => ({
      ...createDefaultField("checkbox", index),
      checkedValue: "true",
      uncheckedValue: "false",
    }),
    SettingsComponent: CheckboxFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  select: {
    type: "select",
    label: "Select Field",
    icon: ChevronsUpDown,
    createField: (index) => ({
      ...createDefaultField("select", index),
      options: ["Option 1", "Option 2"],
    }),
    SettingsComponent: SelectFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  date: {
    type: "date",
    label: "Date Field",
    icon: Calendar,
    createField: (index) => ({
      ...createDefaultField("date", index),
      minDate: undefined,
      maxDate: undefined,
    }),
    SettingsComponent: DateFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  radio: {
    type: "radio",
    label: "Radio Group Field",
    icon: ListChecks,
    createField: (index) => ({
      ...createDefaultField("radio", index),
      options: ["Option 1", "Option 2"],
    }),
    SettingsComponent: ChoiceFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  multiselect: {
    type: "multiselect",
    label: "Multi Select Field",
    icon: ChevronsUpDown,
    createField: (index) => ({
      ...createDefaultField("multiselect", index),
      options: ["Option 1", "Option 2", "Option 3"],
      placeholder: "Select one or more...",
    }),
    SettingsComponent: ChoiceFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  toggle: {
    type: "toggle",
    label: "Toggle Field",
    icon: ToggleLeft,
    createField: (index) => ({
      ...createDefaultField("toggle", index),
      checkedValue: "true",
      uncheckedValue: "false",
      placeholder: undefined,
    }),
    SettingsComponent: CheckboxFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  file: {
    type: "file",
    label: "File Upload Field",
    icon: FileUp,
    createField: (index) => ({
      ...createDefaultField("file", index),
      placeholder: undefined,
      accept: undefined,
      multiple: false,
    }),
    SettingsComponent: FileFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  phone: {
    type: "phone",
    label: "Phone Field",
    icon: Phone,
    createField: (index) => ({
      ...createDefaultField("phone", index),
      placeholder: "(555) 123-4567",
    }),
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  password: {
    type: "password",
    label: "Password Field",
    icon: TextCursorInput,
    createField: (index) => ({
      ...createDefaultField("password", index),
      placeholder: "Enter password",
    }),
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  url: {
    type: "url",
    label: "URL Field",
    icon: Link2,
    createField: (index) => ({
      ...createDefaultField("url", index),
      placeholder: "https://example.com",
    }),
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  time: {
    type: "time",
    label: "Time Field",
    icon: BetweenHorizontalStart,
    createField: (index) => ({
      ...createDefaultField("time", index),
      placeholder: undefined,
    }),
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  dateRange: {
    type: "dateRange",
    label: "Date Range Field",
    icon: Calendar,
    createField: (index) => ({
      ...createDefaultField("dateRange", index),
      placeholder: undefined,
      minDate: undefined,
      maxDate: undefined,
    }),
    SettingsComponent: DateFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  range: {
    type: "range",
    label: "Range Slider Field",
    icon: SlidersHorizontal,
    createField: (index) => ({
      ...createDefaultField("range", index),
      min: 0,
      max: 100,
      step: 1,
      placeholder: undefined,
    }),
    SettingsComponent: NumberFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  rating: {
    type: "rating",
    label: "Rating Field",
    icon: Star,
    createField: (index) => ({
      ...createDefaultField("rating", index),
      placeholder: undefined,
      maxRating: 5,
    }),
    SettingsComponent: RatingFieldSettings,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  heading: {
    type: "heading",
    label: "Heading Block",
    icon: Heading,
    createField: (index) => ({
      ...createDefaultField("heading", index),
      label: "Section heading",
      placeholder: undefined,
      helpText: undefined,
      required: false,
      headingLevel: 2,
    }),
    SettingsComponent: HeadingFieldSettings,
    supportsLabel: true,
    supportsKey: false,
    supportsPlaceholder: false,
    supportsHelpText: false,
    supportsRequired: false,
  },
  paragraph: {
    type: "paragraph",
    label: "Paragraph Block",
    icon: AlignLeft,
    createField: (index) => ({
      ...createDefaultField("paragraph", index),
      label: "Paragraph block",
      placeholder: undefined,
      helpText: undefined,
      required: false,
      content: "Use this paragraph to give extra context before the next field.",
    }),
    SettingsComponent: ParagraphFieldSettings,
    supportsLabel: false,
    supportsKey: false,
    supportsPlaceholder: false,
    supportsHelpText: false,
    supportsRequired: false,
  },
  divider: {
    type: "divider",
    label: "Divider Block",
    icon: Minus,
    createField: (index) => ({
      ...createDefaultField("divider", index),
      label: "Divider block",
      placeholder: undefined,
      helpText: undefined,
      required: false,
    }),
    supportsLabel: false,
    supportsKey: false,
    supportsPlaceholder: false,
    supportsHelpText: false,
    supportsRequired: false,
  },
  section: {
    type: "section",
    label: "Section Block",
    icon: BetweenHorizontalStart,
    createField: (index) => ({
      ...createDefaultField("section", index),
      label: "Section title",
      placeholder: undefined,
      helpText: "Optional section description",
      required: false,
    }),
    supportsLabel: true,
    supportsKey: false,
    supportsPlaceholder: false,
    supportsHelpText: true,
    supportsRequired: false,
  },
};

export const FIELD_PALETTE = Object.values(FIELD_TYPE_DEFINITIONS);

export function createFieldFromType(type: BuilderFieldType, index: number) {
  return FIELD_TYPE_DEFINITIONS[type].createField(index);
}

export function getFieldTypeDefinition(type: BuilderFieldType) {
  return FIELD_TYPE_DEFINITIONS[type];
}
