import {
  AlignLeft,
  BetweenHorizontalStart,
  Calendar,
  CheckSquare,
  ChevronsUpDown,
  FileUp,
  Hash,
  Heading,
  Link2,
  ListChecks,
  Mail,
  Minus,
  Phone,
  Pilcrow,
  SlidersHorizontal,
  Star,
  TextCursorInput,
  ToggleLeft,
  Type,
} from "lucide-react";
import { FIELD_EDITABLE_SETTINGS, createUniqueFieldKey } from "./field-helpers";
import type { BuilderField, BuilderFieldType, FieldTypeDefinition } from "./types";

function createDefaultField(type: BuilderFieldType, index: number, fields: BuilderField[] = []): BuilderField {
  const baseLabel = `${type[0].toUpperCase()}${type.slice(1)} field`;
  return {
    id: crypto.randomUUID(),
    type,
    key: createUniqueFieldKey(`${type}_${index + 1}`, fields),
    label: baseLabel,
    required: true,
    placeholder: type === "checkbox" ? undefined : "Value here...",
    helpText: "Helper text",
    width: "full",
    hidden: false,
  };
}

export const FIELD_TYPE_DEFINITIONS: Record<BuilderFieldType, FieldTypeDefinition> = {
  text: {
    type: "text",
    label: "Text Field",
    icon: Type,
    createField: (index, fields) => createDefaultField("text", index, fields),
    editableSettings: FIELD_EDITABLE_SETTINGS.text,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  email: {
    type: "email",
    label: "Email Field",
    icon: Mail,
    createField: (index, fields) => createDefaultField("email", index, fields),
    editableSettings: FIELD_EDITABLE_SETTINGS.email,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  textarea: {
    type: "textarea",
    label: "TextArea Field",
    icon: Pilcrow,
    createField: (index, fields) => createDefaultField("textarea", index, fields),
    editableSettings: FIELD_EDITABLE_SETTINGS.textarea,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  number: {
    type: "number",
    label: "Number Field",
    icon: Hash,
    createField: (index, fields) => ({
      ...createDefaultField("number", index, fields),
      min: undefined,
      max: undefined,
      step: 1,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.number,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  checkbox: {
    type: "checkbox",
    label: "CheckBox Field",
    icon: CheckSquare,
    createField: (index, fields) => ({
      ...createDefaultField("checkbox", index, fields),
      checkedValue: "true",
      uncheckedValue: "false",
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.checkbox,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  select: {
    type: "select",
    label: "Select Field",
    icon: ChevronsUpDown,
    createField: (index, fields) => ({
      ...createDefaultField("select", index, fields),
      options: ["Option 1", "Option 2"],
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.select,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  date: {
    type: "date",
    label: "Date Field",
    icon: Calendar,
    createField: (index, fields) => ({
      ...createDefaultField("date", index, fields),
      minDate: undefined,
      maxDate: undefined,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.date,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  radio: {
    type: "radio",
    label: "Radio Group Field",
    icon: ListChecks,
    createField: (index, fields) => ({
      ...createDefaultField("radio", index, fields),
      options: ["Option 1", "Option 2"],
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.radio,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  multiselect: {
    type: "multiselect",
    label: "Multi Select Field",
    icon: ChevronsUpDown,
    createField: (index, fields) => ({
      ...createDefaultField("multiselect", index, fields),
      options: ["Option 1", "Option 2", "Option 3"],
      placeholder: "Select one or more...",
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.multiselect,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  toggle: {
    type: "toggle",
    label: "Toggle Field",
    icon: ToggleLeft,
    createField: (index, fields) => ({
      ...createDefaultField("toggle", index, fields),
      checkedValue: "true",
      uncheckedValue: "false",
      placeholder: undefined,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.toggle,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  file: {
    type: "file",
    label: "File Upload Field",
    icon: FileUp,
    createField: (index, fields) => ({
      ...createDefaultField("file", index, fields),
      placeholder: undefined,
      accept: undefined,
      multiple: false,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.file,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  phone: {
    type: "phone",
    label: "Phone Field",
    icon: Phone,
    createField: (index, fields) => ({
      ...createDefaultField("phone", index, fields),
      placeholder: "(555) 123-4567",
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.phone,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  password: {
    type: "password",
    label: "Password Field",
    icon: TextCursorInput,
    createField: (index, fields) => ({
      ...createDefaultField("password", index, fields),
      placeholder: "Enter password",
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.password,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  url: {
    type: "url",
    label: "URL Field",
    icon: Link2,
    createField: (index, fields) => ({
      ...createDefaultField("url", index, fields),
      placeholder: "https://example.com",
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.url,
    supportsLabel: true,
    supportsKey: true,
    supportsPlaceholder: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  time: {
    type: "time",
    label: "Time Field",
    icon: BetweenHorizontalStart,
    createField: (index, fields) => ({
      ...createDefaultField("time", index, fields),
      placeholder: undefined,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.time,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  dateRange: {
    type: "dateRange",
    label: "Date Range Field",
    icon: Calendar,
    createField: (index, fields) => ({
      ...createDefaultField("dateRange", index, fields),
      placeholder: undefined,
      minDate: undefined,
      maxDate: undefined,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.dateRange,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  range: {
    type: "range",
    label: "Range Slider Field",
    icon: SlidersHorizontal,
    createField: (index, fields) => ({
      ...createDefaultField("range", index, fields),
      min: 0,
      max: 100,
      step: 1,
      placeholder: undefined,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.range,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  rating: {
    type: "rating",
    label: "Rating Field",
    icon: Star,
    createField: (index, fields) => ({
      ...createDefaultField("rating", index, fields),
      placeholder: undefined,
      maxRating: 5,
      ratingStep: 1,
      ratingIcon: "star",
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.rating,
    supportsLabel: true,
    supportsKey: true,
    supportsHelpText: true,
    supportsRequired: true,
  },
  heading: {
    type: "heading",
    label: "Heading Block",
    icon: Heading,
    createField: (index, fields) => ({
      ...createDefaultField("heading", index, fields),
      key: undefined,
      label: undefined,
      placeholder: undefined,
      helpText: undefined,
      required: false,
      headingLevel: 2,
      content: "Section heading",
      align: "left",
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.heading,
    supportsLabel: false,
    supportsKey: false,
    supportsPlaceholder: false,
    supportsHelpText: false,
    supportsRequired: false,
  },
  paragraph: {
    type: "paragraph",
    label: "Paragraph Block",
    icon: AlignLeft,
    createField: (index, fields) => ({
      ...createDefaultField("paragraph", index, fields),
      key: undefined,
      label: undefined,
      placeholder: undefined,
      helpText: undefined,
      required: false,
      content: "Use this paragraph to give extra context before the next field.",
      align: "left",
      markdown: false,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.paragraph,
    supportsLabel: false,
    supportsKey: false,
    supportsPlaceholder: false,
    supportsHelpText: false,
    supportsRequired: false,
  },
  divider: {
    type: "divider",
    label: "Divider Block",
    icon: Minus,
    createField: (index, fields) => ({
      ...createDefaultField("divider", index, fields),
      key: undefined,
      label: undefined,
      placeholder: undefined,
      helpText: undefined,
      required: false,
      width: undefined,
      hidden: undefined,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.divider,
    supportsLabel: false,
    supportsKey: false,
    supportsPlaceholder: false,
    supportsHelpText: false,
    supportsRequired: false,
  },
  section: {
    type: "section",
    label: "Section Block",
    icon: BetweenHorizontalStart,
    createField: (index, fields) => ({
      ...createDefaultField("section", index, fields),
      key: undefined,
      label: "Section title",
      placeholder: undefined,
      helpText: "Optional section description",
      required: false,
      collapsible: false,
      collapsed: false,
    }),
    editableSettings: FIELD_EDITABLE_SETTINGS.section,
    supportsLabel: true,
    supportsKey: false,
    supportsPlaceholder: false,
    supportsHelpText: true,
    supportsRequired: false,
  },
};

export const FIELD_PALETTE = Object.values(FIELD_TYPE_DEFINITIONS);

export function createFieldFromType(type: BuilderFieldType, index: number, fields: BuilderField[] = []) {
  return FIELD_TYPE_DEFINITIONS[type].createField(index, fields);
}

export function getFieldTypeDefinition(type: BuilderFieldType) {
  return FIELD_TYPE_DEFINITIONS[type];
}
